import Link from "next/link";
import { ArrowRight, Beaker, BookOpenCheck, Lightbulb, Plus } from "lucide-react";
import { ExperimentCard } from "@/components/experiment-card";
import { currentCitizen } from "@/lib/auth";
import { dashboardData } from "@/lib/queries";
export default async function DashboardPage({ searchParams }: { searchParams: Promise<{ welcome?: string }> }) {
  const citizen = await currentCitizen(); if (!citizen) return null; const data = await dashboardData(citizen.id); const { welcome } = await searchParams;
  const recruiting = data.experiments.filter(item => item.status === "Recruiting"); const completed = data.experiments.filter(item => item.status === "Completed");
  return <div className="shell py-12"><header className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="eyebrow">Citizen lab</p><h1 className="serif mt-4 text-5xl font-bold tracking-[-.05em]">Good {new Date().getHours() < 12 ? "morning" : new Date().getHours() < 18 ? "afternoon" : "evening"}, {citizen.displayName.split(" ")[0]}.</h1><p className="mt-4 text-[var(--muted)]">Here is what the community is trying to learn—not what it wants you to scroll.</p></div><Link href="/app/create" className="btn btn-primary"><Plus size={15} /> Propose something</Link></header>{welcome ? <div className="alert mt-8 !border-[var(--moss)]"><strong>You’re a founding citizen.</strong> Start by inspecting an experiment or proposing one careful idea.</div> : null}
    <section className="mt-14"><div className="flex items-center justify-between"><div><p className="eyebrow">Your experiments</p><h2 className="serif mt-3 text-3xl font-bold">Commitments you chose</h2></div><Beaker className="text-[var(--oxide)]" /></div><div className="mt-5 grid gap-3">{data.joined.length ? data.joined.map(item => <Link href={`/app/experiments/${item.slug}`} key={item.id} className="paper flex items-center justify-between gap-4 p-5 no-underline"><div><strong>{item.title}</strong><p className="mt-1 text-xs text-[var(--muted)]">{item.withdrawnAt ? "Withdrawn" : item.status}</p></div><ArrowRight size={16} /></Link>) : <div className="border border-dashed border-[var(--line)] p-6 text-sm text-[var(--muted)]">You have not joined an experiment yet. Opt-in only when the question and terms make sense to you.</div>}</div></section>
    <section className="mt-14"><div className="flex items-end justify-between gap-4"><div><p className="eyebrow">Recruiting now</p><h2 className="serif mt-3 text-3xl font-bold">Small tests, explicit terms</h2></div><Link href="/experiments" className="text-xs font-bold">Public catalogue</Link></div><div className="mt-5 grid gap-5 md:grid-cols-2">{recruiting.map(experiment => <ExperimentCard key={experiment.id} experiment={experiment} hrefPrefix="/app/experiments" />)}</div></section>
    <section className="mt-14 grid gap-8 lg:grid-cols-2"><div><div className="flex items-center justify-between"><div><p className="eyebrow">Goals needing ideas</p><h2 className="serif mt-3 text-3xl font-bold">Where the environment falls short</h2></div><Lightbulb className="text-[var(--indigo)]" /></div><div className="mt-5 grid gap-3">{data.goals.map(goal => <Link href={`/app/goals/${goal.slug}`} key={goal.id} className="paper block p-5 no-underline"><div className="flex items-center justify-between"><span className="eyebrow">{goal.domain}</span><span className="text-xs font-bold">{goal.ideaCount} ideas</span></div><h3 className="serif mt-4 text-xl font-bold">{goal.title}</h3><div className="mt-4 flex gap-6 text-xs"><span><span className="text-[var(--muted)]">Current</span><br /><strong>{goal.baseline}</strong></span><span><span className="text-[var(--muted)]">Target</span><br /><strong>{goal.desiredTarget}</strong></span></div></Link>)}</div></div>
      <div><div className="flex items-center justify-between"><div><p className="eyebrow">Community decisions</p><h2 className="serif mt-3 text-3xl font-bold">Evidence awaiting judgment</h2></div><BookOpenCheck className="text-[var(--moss)]" /></div><div className="mt-5 grid gap-3">{completed.map(item => <Link href={`/app/experiments/${item.slug}`} key={item.id} className="paper flex items-center justify-between gap-4 p-5 no-underline"><div><span className="eyebrow">Completed · {item.domain}</span><h3 className="serif mt-3 text-xl font-bold">{item.title}</h3><p className="mt-2 text-xs text-[var(--muted)]">Review limitations and submit Scale / Modify / Repeat / Stop.</p></div><ArrowRight size={17} /></Link>)}</div><div className="mt-8 border-l-2 border-[var(--oxide)] pl-5"><p className="eyebrow">Recent learning</p><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Seeded walking-group results suggest a modification—not scale. The visible limitation is the learning: demo data, self-reporting, and no comparison group cannot support a causal claim.</p></div></div></section>
    <section className="mt-16 border-t hairline pt-8"><details className="text-xs text-[var(--muted)]"><summary className="cursor-pointer font-bold text-[var(--ink)]">Account and privacy</summary><p className="mt-3 max-w-xl leading-5">Deleting your account removes your login, participation, supports, signals, and comments. Public aggregate demo records remain. This action cannot be undone.</p><form action="/api/account" method="post"><button className="mt-3 border-0 bg-transparent p-0 font-bold text-[var(--oxide-dark)] underline" type="submit">Delete my account</button></form></details></section>
  </div>;
}
