import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { listGoals, listIdeasForCreate } from "@/lib/queries";
export const dynamic = "force-dynamic";
type Tab = "goal" | "idea" | "experiment";
export default async function CreatePage({ searchParams }: { searchParams: Promise<{ tab?: string; goal?: string; error?: string }> }) {
  const query = await searchParams; const tab: Tab = query.tab === "idea" || query.tab === "experiment" ? query.tab : "goal"; const [goals, ideas] = await Promise.all([listGoals(), listIdeasForCreate()]);
  return <div className="shell py-12"><Link href="/app" className="inline-flex items-center gap-2 text-xs font-bold no-underline"><ArrowLeft size={14} /> Back to lab</Link><header className="mt-8 max-w-3xl"><p className="eyebrow">Structured proposal</p><h1 className="serif mt-4 text-5xl font-bold tracking-[-.05em]">Think like an experiment.</h1><p className="mt-4 leading-7 text-[var(--muted)]">The form is part of the method: name the outcome, mechanism, downside, measurement, guardrail, and privacy cost before asking people to participate.</p></header><nav className="mt-8 flex flex-wrap gap-2" aria-label="Creation type">{(["goal","idea","experiment"] as const).map(item => <Link key={item} href={`/app/create?tab=${item}`} className={`btn ${tab === item ? "btn-primary" : "btn-ghost"}`}>{item === "goal" ? "Create goal" : item === "idea" ? "Propose idea" : "Propose experiment"}</Link>)}</nav>{query.error ? <div className="alert mt-6">{query.error}</div> : null}
    {tab === "goal" ? <form action="/api/goals" method="post" className="paper mt-8 grid gap-6 p-6 sm:p-9"><div><p className="eyebrow">01 · Desired outcome</p><h2 className="serif mt-3 text-3xl font-bold">Create a measurable community goal</h2></div><Field name="title" label="Goal title" help="Describe the outcome, not a solution." placeholder="Increase voluntary…" /><Field name="description" label="What do you want to improve?" textarea /><div className="field"><label htmlFor="domain">Domain</label><select className="input" id="domain" name="domain" required>{["Health","Learning","Social","Contribution","Governance"].map(domain => <option key={domain}>{domain}</option>)}</select></div><div className="grid gap-5 sm:grid-cols-3"><Field name="targetMetric" label="Target metric" placeholder="Minutes / week" /><Field name="baseline" label="Current baseline" placeholder="80 minutes / week" /><Field name="desiredTarget" label="Desired target" placeholder="150 minutes / week" /></div><Field name="reasoning" label="Why does the environment contribute to this problem?" textarea /><button type="submit" className="btn btn-primary justify-self-start">Create goal</button></form> : null}
    {tab === "idea" ? <form action="/api/ideas" method="post" className="paper mt-8 grid gap-6 p-6 sm:p-9"><div><p className="eyebrow">02 · Environmental change</p><h2 className="serif mt-3 text-3xl font-bold">Propose an intervention</h2></div><div className="field"><label htmlFor="goalId">Linked goal</label><select className="input" id="goalId" name="goalId" required defaultValue={query.goal}>{goals.map(goal => <option value={goal.id} key={goal.id}>{goal.title}</option>)}</select></div><Field name="title" label="Idea title" /><Field name="explanation" label="What changes in the environment?" help="Describe the intervention, not just the feature." textarea /><Field name="hypothesis" label="Falsifiable hypothesis" help="If we change X, we expect Y, because Z." textarea /><Field name="expectedEffect" label="Expected effect" /><Field name="estimatedCost" label="Estimated cost" /><Field name="potentialDownsides" label="Potential downsides" help="Who could be excluded, pressured, harmed, or mismeasured?" textarea /><button type="submit" className="btn btn-primary justify-self-start">Propose idea</button></form> : null}
    {tab === "experiment" ? <form action="/api/experiments" method="post" className="paper mt-8 grid gap-6 p-6 sm:p-9"><div><p className="eyebrow">03 · Small test</p><h2 className="serif mt-3 text-3xl font-bold">Propose an experiment</h2><p className="mt-3 text-sm leading-6 text-[var(--muted)]">New experiments start as drafts. A moderator reviews safety, privacy, clarity, and recruitment before changing state.</p></div><div className="field"><label htmlFor="ideaId">Linked idea</label><select className="input" id="ideaId" name="ideaId" required>{ideas.map(idea => <option value={idea.id} key={idea.id}>{idea.goalTitle} — {idea.title}</option>)}</select></div><Field name="title" label="Experiment title" /><Field name="question" label="Question" help="What, exactly, are we trying to learn?" textarea /><Field name="hypothesis" label="Hypothesis" textarea /><Field name="description" label="Short description" textarea /><Field name="intervention" label="Intervention" help="What changes for a participant?" textarea /><div className="grid gap-5 sm:grid-cols-2"><Field name="participantTarget" label="Participant target" type="number" defaultValue="20" /><Field name="durationDays" label="Duration in days" type="number" defaultValue="14" /></div><Field name="participantEligibility" label="Participant eligibility" textarea /><Field name="baseline" label="Baseline" /><Field name="primaryMetric" label="Primary metric" help="Choose one measure that most directly tests the hypothesis." /><Field name="secondaryMetrics" label="Secondary metrics" help="Comma-separated." /><Field name="guardrails" label="Guardrails" help="Comma-separated outcomes that must not get worse." /><Field name="timeBurden" label="Participant time burden" /><Field name="dataCollected" label="Data collected and why" textarea /><Field name="privacyNotes" label="Privacy: public vs private" textarea /><button type="submit" className="btn btn-primary justify-self-start">Create draft experiment</button></form> : null}
  </div>;
}

function Field({ name, label, help, placeholder, textarea = false, type = "text", defaultValue }: { name: string; label: string; help?: string; placeholder?: string; textarea?: boolean; type?: string; defaultValue?: string }) {
  return <div className="field"><label htmlFor={name}>{label}</label>{textarea ? <textarea className="input" id={name} name={name} required minLength={10} maxLength={1500} placeholder={placeholder} /> : <input className="input" id={name} name={name} type={type} required placeholder={placeholder} defaultValue={defaultValue} />}{help ? <small>{help}</small> : null}</div>;
}
