import type { Metadata } from "next";
import Link from "next/link";
import { redirect } from "next/navigation";
import { currentCitizen } from "@/lib/auth";
export const metadata: Metadata = { title: "Become a citizen" };
export const dynamic = "force-dynamic";
export default async function JoinPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  if (await currentCitizen()) redirect("/app"); const { error } = await searchParams;
  return <div className="shell grid min-h-[75vh] items-center gap-12 py-16 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Founding cohort</p><h1 className="serif mt-6 text-6xl font-bold leading-[.95] tracking-[-.055em]">Become a citizen, not a user.</h1><p className="mt-6 text-lg leading-8 text-[var(--muted)]">Citizens can propose goals, design interventions, join experiments voluntarily, challenge conclusions, and help decide what to test next.</p><ul className="mt-8 grid gap-3 text-sm"><li>✓ No public reputation score</li><li>✓ No hidden experiments</li><li>✓ Withdraw at any time</li><li>✓ Delete your account</li></ul></div><form className="paper p-7 sm:p-10" action="/api/auth/signup" method="post"><div><p className="eyebrow">Create your account</p><h2 className="serif mt-4 text-3xl font-bold">Join the experiment</h2></div>{error ? <p className="alert mt-5 text-sm">{error}</p> : null}<div className="mt-7 grid gap-5"><div className="field"><label htmlFor="displayName">Display name</label><input className="input" id="displayName" name="displayName" required minLength={2} maxLength={60} autoComplete="name" /></div><div className="field"><label htmlFor="email">Email</label><input className="input" id="email" name="email" type="email" required autoComplete="email" /></div><div className="field"><label htmlFor="password">Password</label><input className="input" id="password" name="password" type="password" required minLength={10} maxLength={128} autoComplete="new-password" /><small>At least 10 characters. Passwords are salted and hashed.</small></div></div><button className="btn btn-primary mt-7 w-full" type="submit">Become a founding citizen</button><p className="mt-5 text-center text-xs text-[var(--muted)]">Already a citizen? <Link href="/login" className="font-bold text-[var(--ink)]">Sign in</Link></p></form></div>;
}
