import Link from "next/link";
import { ArrowLeft, ArrowRight, Heart, Plus } from "lucide-react";
import { notFound } from "next/navigation";
import { getGoal } from "@/lib/queries";
export const dynamic = "force-dynamic";
type Props = { params: Promise<{ id: string }>; searchParams: Promise<{ success?: string; idea?: string }> };
export default async function GoalPage({ params, searchParams }: Props) {
  const data = await getGoal((await params).id); if (!data) notFound(); const query = await searchParams; const { goal } = data;
  return <div className="shell py-12"><Link href="/app" className="inline-flex items-center gap-2 text-xs font-bold no-underline"><ArrowLeft size={14} /> Back to lab</Link>{query.success || query.idea ? <div className="alert mt-6 !border-[var(--moss)]">{query.success ?? "Idea proposed. It remains a proposal until tested."}</div> : null}<header className="mt-8 grid gap-10 border-b hairline pb-12 lg:grid-cols-[1fr_auto]"><div><div className="flex gap-2"><span className="tag">{goal.domain}</span><span className="tag">{goal.status}</span>{goal.isDemo ? <span className="tag !text-[var(--oxide-dark)]">Demo baseline</span> : null}</div><h1 className="serif mt-7 max-w-4xl text-6xl font-bold leading-[.96] tracking-[-.055em]">{goal.title}</h1><p className="mt-6 max-w-3xl text-xl leading-8 text-[var(--muted)]">{goal.description}</p></div><Link href={`/app/create?tab=idea&goal=${goal.id}`} className="btn btn-primary self-end"><Plus size={15} /> Propose idea</Link></header><section className="metric-grid mt-10"><div><span className="eyebrow">Baseline</span><strong className="serif mt-3 block text-2xl">{goal.baseline}</strong></div><div><span className="eyebrow">Desired target</span><strong className="serif mt-3 block text-2xl">{goal.desiredTarget}</strong></div><div><span className="eyebrow">Metric</span><strong className="mt-3 block text-sm">{goal.targetMetric}</strong></div></section><section className="mt-10 border-l-2 border-[var(--indigo)] pl-5"><p className="eyebrow">Why this matters</p><p className="mt-3 max-w-3xl leading-7 text-[var(--muted)]">{goal.reasoning}</p></section>
    <section className="mt-16"><div><p className="eyebrow">Environmental interventions</p><h2 className="serif mt-3 text-4xl font-bold">Ideas, not answers</h2></div><div className="mt-6 grid gap-5 md:grid-cols-2">{data.ideas.map(idea => <article className="paper p-6" key={idea.id}><div className="flex items-center justify-between"><span className="text-xs font-bold text-[var(--muted)]">{idea.supportCount} supporters</span>{idea.isDemo ? <span className="eyebrow">Seed idea</span> : null}</div><h3 className="serif mt-5 text-2xl font-bold">{idea.title}</h3><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{idea.explanation}</p><div className="mt-5 border-l-2 border-[var(--oxide)] pl-4 text-sm"><strong>Hypothesis</strong><p className="mt-1 leading-6 text-[var(--muted)]">{idea.hypothesis}</p></div><dl className="mt-5 grid grid-cols-2 gap-4 text-xs"><div><dt className="text-[var(--muted)]">Expected effect</dt><dd className="mt-1 font-bold">{idea.expectedEffect}</dd></div><div><dt className="text-[var(--muted)]">Estimated cost</dt><dd className="mt-1 font-bold">{idea.estimatedCost}</dd></div></dl><details className="mt-5 text-xs"><summary className="cursor-pointer font-bold">Potential downsides</summary><p className="mt-2 leading-5 text-[var(--muted)]">{idea.potentialDownsides}</p></details><form action={`/api/ideas/${idea.id}/support`} method="post" className="mt-5"><input type="hidden" name="returnTo" value={`/app/goals/${goal.slug}`} /><button type="submit" className="btn btn-ghost"><Heart size={14} /> Support exploring this</button></form></article>)}</div></section>
    <section className="mt-16"><p className="eyebrow">Experiments</p><h2 className="serif mt-3 text-4xl font-bold">Tests connected to this goal</h2><div className="mt-6 grid gap-3">{data.experiments.length ? data.experiments.map(experiment => <Link href={`/app/experiments/${experiment.slug}`} key={experiment.id} className="paper flex items-center justify-between gap-5 p-5 no-underline"><div><span className="eyebrow">{experiment.status} · {experiment.durationDays} days</span><h3 className="serif mt-2 text-xl font-bold">{experiment.title}</h3><p className="mt-1 text-sm text-[var(--muted)]">{experiment.question}</p></div><ArrowRight className="shrink-0" size={18} /></Link>) : <div className="border border-dashed border-[var(--line)] p-6 text-sm text-[var(--muted)]">No experiment yet. A good idea still needs metrics, guardrails, privacy, and an opt-in protocol.</div>}</div></section>
  </div>;
}
